name: Keep Render App Awake

on:
  schedule:
    - cron: "*/13 * * * *" # every 13 minutes
  workflow_dispatch:       # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Render app
        run: curl -s https://license-manager-f1ps.onrender.com/rest/api/check
        
